version = 0.1

[default.deploy.parameters]
stack_name = "flowguard-dev"
resolve_s3 = true
s3_prefix = "flowguard-dev"
region = "eu-west-2"
profile = "flowguard-dev"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev\" FrontendOrigin=\"http://localhost:5173\""
